// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9kXxlFD6x_h_J11dWS7750qNT4ix-p6A',
    appId: '1:427667244857:web:d034bc7c3507aacbd90ae8',
    messagingSenderId: '427667244857',
    projectId: 'flutterauthproject-d811f',
    authDomain: 'flutterauthproject-d811f.firebaseapp.com',
    storageBucket: 'flutterauthproject-d811f.appspot.com',
    measurementId: 'G-050VD10MXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZQKBAInSkqE2oP3hPSHMFvEranhGwK0',
    appId: '1:427667244857:android:b1e06277361addf1d90ae8',
    messagingSenderId: '427667244857',
    projectId: 'flutterauthproject-d811f',
    storageBucket: 'flutterauthproject-d811f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgBaIy_Et5kIYnrVhfZH_H9uI8IFtrDM',
    appId: '1:427667244857:ios:822c6f430f125e02d90ae8',
    messagingSenderId: '427667244857',
    projectId: 'flutterauthproject-d811f',
    storageBucket: 'flutterauthproject-d811f.appspot.com',
    iosBundleId: 'com.example.flutterAuthProject',
  );
}
